apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: frhov5pst-go 
  janus-idp.io/tekton: frhov5pst-go
  backstage.io/kubernetes-id: frhov5pst-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: frhov5pst-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml